# .github/workflows/git-sync.yml
#jall
on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "rikard-swahn/barney"
          source_branch: "master"
          destination_repo: "rikard-swahn/barney-mirror"
          destination_branch: "master"
          source_ssh_private_key: ${{ secrets.SYNC_SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.SYNC_DEST_SSH_PRIVATE_KEY }}